WebSite/Controllers/ContactController.cs
using Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
//using System.Web.Mail;
using System.Web.Mvc;


namespace WebSite
{
    public class ContactController : BaseController
    {
        //
        // GET: /Contact/
        
        public ActionResult Index()
        {
            return View();


        }


        public ActionResult Confirmation()
        {

            return View();

        }

        [HttpPost]
        public ActionResult Index(Message m)
        {
            //m.OKMsg = true;
            //return View(model: m);
            if (ModelState.IsValid)
            {
                try
                {
                    //const string SERVER = "relay-hosting.secureserver.net";
                    //System.Web.Mail.MailMessage oMail = new System.Web.Mail.MailMessage();
                    //oMail.From = new MailAddress("noyaschleien@noyaschleien.com").Address;
                    //oMail.To = "noyaschleien@gmail.com";
                    //oMail.Subject = "noyaschleien.com";
                    //oMail.BodyFormat = MailFormat.Text;	// enumeration
                    //oMail.BodyEncoding = System.Text.Encoding.UTF8;
                    //oMail.Priority = System.Web.Mail.MailPriority.High;	// enumeration
                    //string senderName = m.SenderName;
                    //string senderEmail = m.Email;
                    //string senderMessage = m.Content;

                    //oMail.Body = string.Format("{0}\n{1}\n{2}\n{3}\n{4}\n{5}\n{6}", senderName, senderEmail, senderMessage, Request.Browser, Request.UserAgent, Request.UserHostAddress, Request.UserHostName);
                    //SmtpMail.SmtpServer = SERVER;
                    //SmtpMail.Send(oMail);
                    //oMail = null;	// free up resources  
                    //return RedirectToAction("Index");

                    MailAddress mailfrom = new MailAddress("noyaschleien@noyaschleien.com");
                    MailAddress mailto = new MailAddress("liorgish@gmail.com");
                    MailMessage newmsg = new MailMessage(mailfrom, mailto);
                    string senderName = m.SenderName;
                    string senderEmail = m.Email;
                    string senderMessage = m.Content;
                    newmsg.Subject = "noyaschleien@noyaschleien.com";
                    newmsg.Body = string.Format("{0}\n{1}\n{2}\n{3}\n{4}\n{5}\n{6}", senderName, senderEmail, senderMessage, Request.Browser, Request.UserAgent, Request.UserHostAddress, Request.UserHostName);

                    SmtpClient smtp = new SmtpClient("relay-hosting.secureserver.net", 25);
                    smtp.Send(newmsg);

                    return RedirectToAction("Confirmation");
                }
                catch (Exception)
                {


                }
            }




            // If we got this far, something failed, redisplay form

            return View();
        }
    }
}

WebSite/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Helpers;

namespace WebSite
{
    public class LinksController : BaseController
    {
        private WebDBEntities db = new WebDBEntities();
        //
        // GET: /Links/
        public async Task<ActionResult> Index()
        {
           return View(await db.Links.ToListAsync());
        }
	}
}

WebSite/Controllers/PicturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Helpers;

namespace WebSite
{
    public class PicturesController : BaseController
    {
        private WebDBEntities db = new WebDBEntities();
        //
        // GET: /Pictures/
        public  ActionResult Index()
        {
            return View();
        }
	}
}

WebSite/Controllers/VideosController.cs
using Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebSite
{
    public class VideosController : BaseController
    {
        //
        // GET: /Videos/
        public ActionResult Index()
        {
            return View();
        }
	}
}

WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="@Helpers.CultureHelper.GetCurrentNeutralCulture()" dir="@(Helpers.CultureHelper.IsRighToLeft() ? "rtl":"ltr")">
@using StackExchange.Profiling;
@{
    bool heb = Helpers.CultureHelper.IsRighToLeft();
    string fl = heb ? "float:left" : "float:right";
    string lf = heb ? "float:right" : "float:left";
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, height=device-height,  initial-scale=1.0, user-scalable=no;user-scalable=0;" />
    <title>Noya Schleien| @ViewBag.Title</title>
    <meta name="description" content="Marimba & Percussion artist, Noya Schleien. @ViewBag.Title Noya." />

    @*<link href='http://fonts.googleapis.com/css?family=Rock+Salt' rel='stylesheet' type='text/css'>*@
    @{
        if (heb)
        {
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

            <link href="~/Content/bootstrap-rtl.css" rel="stylesheet" />
        }
        else
        {
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        }
    }



    @* @System.Web.Optimization.Styles.Render("~/Content/css")*@
    @*<link href="~/Content/myStyle.css" rel="stylesheet" />*@

    @RenderSection("head", false)
</head>
<body>

    <div class="container body-content">
        <div style="color: white; -moz-border-radius: 20px; -webkit-border-radius:20px; border-radius:20px"></div>

        <div style="background-image: url('../Images/headers_pic/@(ViewBag.ImageName+".jpg")');" id="bg">
            <div class="rotatorTextName">@Resources.NoyaSchleien</div>
            <div class="rotatorTextTitle">@Resources.Title</div>
        </div>
        @*<div id="bg">
                     <div class="jumbotron well alert alert-danger" style="font-family: 'Rock Salt', cursive; text-align: center;margin-bottom:0px " id="logo">@Resources.NoyaSchleien</div>
            </div>*@

        <div dir="ltr" class="btn-group-sm">
            @Html.ActionLink("Eng", "SetCulture", "Culture", new { culture = "en", url = @Request.Url }, new { @class = "langLinks" })
            @Html.ActionLink("עברית", "SetCulture", "Culture", new { culture = "he", url = @Request.Url }, new { @class = "langLinks" })


        </div>
        @*<script>
                $("#langLinks").click(function () {

                    var aaa = @Url.Action("Culture", "SetCulture");
                    var culture = $(this).attr("data-culture");
                    var returnUrl = $(location).attr('href');
                    $.get(url, { culture: culture, url: returnUrl });
                });
            </script>*@
        <div class="navbar navbar-default" style="">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" style="@lf" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span style="font-weight: 900; color: white">@Resources.Menu</span>
                    </button>
                    <h4 class="navMenu hidden-lg hidden-md hidden-sm mobliePath">
                        <span>@Resources.NoyaSchleien</span>
                        <span>|</span>
                        <span>@ViewBag.Title</span>

                    </h4>

                </div>
                <div class="navbar-collapse collapse">
                    <ul class="menu-ul nav nav-pills nav-justified ">
                        <li class="menuItem">@Html.ActionLink(@Resources.Home, "Index", "Home", null, new { @class = "Home" })</li>
                        <li class="menuItem">@Html.ActionLink(@Resources.Biography, "Index", "Biography", null, new { @class = "Biography" })</li>
                        <li class="menuItem">@Html.ActionLink(@Resources.Pictures, "Index", "Pictures", null, new { @class = "Pictures" })</li>
                        <li class="menuItem">@Html.ActionLink(@Resources.Videos, "Index", "Videos", null, new { @class = "Videos" })</li>
                        <li class="menuItem">@Html.ActionLink(@Resources.Programs, "Index", "Programs", null, new { @class = "Programs" })</li>
                        <li class="menuItem">@Html.ActionLink(@Resources.Links, "Index", "Links", null, new { @class = "Links" })</li>
                        <li class="menuItem">@Html.ActionLink(@Resources.Contact, "Index", "Contact", null, new { @class = "Contact" })</li>
                    </ul>
                </div>
            </div>
        </div>

        @RenderBody()
        <footer class="row">
            @*<hr id="hrFooter" />*@
            <div class="footerItems container-fluid">

                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="footer-mail">noyaschleien@gmail.com</div>
                    @*  @Html.ActionLink(@Resources.PressHere, "Index", "Contact", null, new { @class = "", })*@

                </div>
                <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-12 footerBtnWrapper">
                    @Html.ActionLink(@Resources.OrderConcert, "Index", "Contact", null, new { @class = "footer-btn btn btn-primary" })

                </div>
            </div>
        </footer>
        <hr class="logoHR" />
        <p class="credits">© Noya Schleien 2013 | Developed by @Html.ActionLink("Future WebSites", "Index", "Home", null, new { @class = "logo" }) </p>

    </div>
    @*@System.Web.Optimization.Scripts.Render("~/bundles/scripts")
        @System.Web.Optimization.Scripts.Render("~/bundles/scripts2")*@

    <link href="~/Content/myStyle.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.1.1.min.js"></script>
    <script src="~/Scripts/generalScripts.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/respond.js"></script>
    <script src="~/Scripts/myScripts.js"></script>
   @* <link href="~/Content/bootstrap-rtl.css" rel="stylesheet" />*@
    <script src="~/Scripts/homeScripts.js"></script>
    <script src="~/youmax/js/jquery.youmax.min.js"></script>
    <link href="youmax/css/youmax_trend.min.css" rel="stylesheet" />
    @RenderSection("scripts", required: false)>
</body>
</html>

WebSite/Views/Shared/_LayoutManage.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title|Noya Schleien</title>
    <meta name="description" content="Marimba & Percussion artist, Noya Schleien. @ViewBag.Title Noya." />
    @System.Web.Optimization.Scripts.Render("~/bundles/jquery")
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryval")
    @System.Web.Optimization.Styles.Render("~/Content/css")
    @System.Web.Optimization.Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/SpaceLab.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Rock+Salt' rel='stylesheet' type='text/css'>
    
</head>
<body>

    <div class="container body-content">

        <div class="jumbotron well alert alert-danger" style="font-family: 'Rock Salt', cursive; text-align: center; " id="logo">NOYA SCHLEIEN</div>
        <div class="navbar navbar-inverse " style="align-content:center;text-justify:auto;text-align:center">
            <div class=" container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @*  @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })*@
                </div>
                <div class="navbar-collapse collapse ">
                    <ul class="nav nav-pills nav-justified ">

                        <li>@Html.ActionLink("Biography", "Index", "ManageBiography")</li>
                        <li>@Html.ActionLink("Manage Hot Updates", "Index", "ManageHotUpdates")</li>
                        <li>@Html.ActionLink("Pictures", "Index", "ManageImagesGallery")</li>
                        <li>@Html.ActionLink("Programs", "Index", "ManagePrograms")</li>
                        <li>@Html.ActionLink("Links", "Index", "ManageLinks")</li>
                        <li>@Html.ActionLink("PressReviews", "Index", "ManagePressReviews")</li>
                        <li>@Html.ActionLink("CalendarEvents", "Index", "ManageCalendarEvents")</li>
                    </ul>
                </div>
            </div>
        </div>

        @RenderBody()
       
        <footer></footer>
    </div>


    @System.Web.Optimization.Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>